name: manage-azure-policy-04c1828b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/deploylifecyclemanagement_mgmt_32c074ea-ddb1-4301-8eae-f182b173cd39/**'
#      - 'policies/flowlog_785144af-b539-4c9e-af5b-4d18789d22d6/**'
#      - .github/workflows/manage-azure-policy-04c1828b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.SEC1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/deploylifecyclemanagement_mgmt_32c074ea-ddb1-4301-8eae-f182b173cd39/**
          policies/flowlog_785144af-b539-4c9e-af5b-4d18789d22d6/**
          policies/test1/**
          policies/storageaccounttlssetting_1b1a80a0-2013-4b00-80f1-2f4419eaf2ee/**
